### PR TITLE
Fixed amiitool crash (@azsde), samsung crash (@Kidel) and added Wolf Link editor (@masterchan-777 @possi)

### PR DESCRIPTION
**Pull request by Kidel**
Everything seems to be working fine on my phones. 
After fixing the errors on the main branch I've also merged with @azsde 's fork to resolve the conflicts.

### CODE REVIEW

**Comment by rathren** [comment]
I am a noob and I am getting the crash on my galaxy phone. I would get a amiibo but they are all sold out :/ any chance I can get a .apk of this version you made? Because I don't know how to install something on my phone withouthaving a .apk. Thank you so much for your work :)

**Comment by Kidel** [comment]
Sorry, but you'll have to wait for the author of this repository to accept this pull request and release an apk. It's not fair if I do it.

**Comment by rathren** [comment]
ok thank you so much I will try it!

**Comment by rathren** [comment]
whoo I finaly got it to run. But when I hold the amiibo under the phone to write the tag it immediately says:

Error while writing main data (stage 1)
java.io.IO.Exception: Transceive

I don't have a NFC card so I was using a amiibo I already got as NFC card. I could nowhere find out if this is even possible or not but I guessed it is. Do you think I did something wrong when building or is it not possible to use a amiibo instead of a NFC card?

**Comment by Kidel** [comment]
Amiibo is already written. You need an empty nfc 215

**Comment by Flecktarnfarbe** [comment]
@Kidel NFC Tags arrived today and I have the same error when writing on a new Tag in Auto Mode

**Comment by sabatashi** [comment]
Hope this gets committed looks good

**Comment by sabatashi** [comment]
I was able to compile it and it looks good, was wondering though I could've sworn there was an SSB editor when scanning SSB amiibo's? But I don't see SSB editor box just the hex viewer when scanning SSB stuff, I do see the edit TP data when scanning wolf link though. Did I somehow mess up the compile or is SSB editor not working?

**Comment by infirit** [comment]
For anyone who is tired of waiting or does not want to build from source version 2.3 works fine for me.

after 3 months of waiting for @HiddenRambler should he be considered mia?

**Comment by xxBigRonxx** [comment]
I was able to build my own using the latest source.  Was not difficult at all.  Thanks to Kidel for fixing several known issues.

**Comment by Nomelas** [comment]
Thanks @Kidel 

I did notice one issue with this though, SSB editing appears to be gone now. though Wolf Link one works fine.

**Comment by sabatashi** [comment]
I believe the SSB Editor was still working when it got removed, but the problem was that it would crash the APP if you try to scan a non SSB amiibo so I think it should be readded but maybe with a disclaimer.

**Comment by Nomelas** [comment]
The wolf link editing option doesn't appear unless you scan/load the wolf link amiibo. I think the same can be done for ssb no?

**Comment by elementcorp** [comment]
I want to thank you all! I made it work smoothly on and old Samsung Note 3 running lollipop 5.0, my wife had on a drawer.  It took me a couple of hours (with all your guidance off course and after a few bumps in the way) to learn how to do it. Even for someone like me who has never touch any mobile development tool. My special thanks to @Kidel @HiddenRambler and @rathren for keeping this thread discussion.

**Comment by Bombastisch** [comment]
God thanks!

The SSB feature wasn't actually removed. He just made the button invisible, because of the known issues mentioned by _sabatashi_ before.

> I believe the SSB Editor was still working when it got removed, but the problem was that it would crash the APP if you try to scan a non SSB amiibo so I think it should be readded but maybe with a disclaimer.

You can make the buttons easily visible in Android Studio, but the problems still occur!
I'm not good at programming, but a simple text that says: "No SSB data found" instead of the app crashing would fix the problem I guess.

**Comment by Bombastisch** [comment]
When will HidddenRambler ever merge this pull request? It can't just be that such a awesome project dies out, because of that...

**Pull request merged**
