### PR TITLE
Add Amiibo File Browser activity

### PR DESCRIPTION
**Pull request by North101**
Still a WIP. Need to add an option to use a file browser instead and set where to scan.

Scans your internal storage for amiibos and displays them in a filterable and sortable list view.

(Based on my "Show more info branch)

screenshot_20170728-180805
screenshot_20170728-180815
screenshot_20170728-180832
screenshot_20170728-180846
screenshot_20170728-180840
screenshot_20170728-180931

### CODE REVIEW

**Comment by Bombastisch** [comment]
OMG, this is soooo cool!  Great idea! This concept makes looking for your amiibo so much easier. Thank you!

**Comment by North101** [comment]
I've finished.

Added a settings activity.
Browser activity now looks for amiibo files in just the tagmo dir otherwise it'd be too slow.
Added pull to refresh.

**Comment by North101** [comment]
screenshot_20170729-221547
screenshot_20170729-221514
screenshot_20170729-221519

**Comment by Bombastisch** [comment]
MERGE MERGE 😱

**Comment by Bombastisch** [comment]
Does "Import Custom Amiibo Database" let you choose a file itself or does it download the file automatically from the third-party link if mentioned sonewhere before?

**Comment by North101** [comment]
@Bombastisch No, it only imports a local json file. If you can think of a better way to word it or anything else I'd be happy to change it

**Comment by Bombastisch** [comment]
Instead of loading the file from your phone, the app could download the file itself from this site:

http://www.amiiboapi.com/api/amiibo

The list is made by N3vin and according to his AmiiboAPI project on github, that list is regulary updated with the newest data.

This would make updating the amiibo list much easier!

**Comment by HiddenRambler** [comment]
Sorry for taking so long, but it's all merged in now. A new release with all the changes are available. This is great stuff @North101, thank you.

**Comment by North101** [comment]
@HiddenRambler No problem, happy to contribute. It also gave me some time to clean up some code. I think there can some improvements to how text is worded for some things I've changed/added.

**Comment by HiddenRambler** [comment]
i've created an organsation on github and moved tagmo into it. I'm hoping that way i can share commit access with others. @North101 I've sent you an invite if you accept it i will try to grant you commit permissions.

**Comment by North101** [comment]
@HiddenRambler Thanks, I've accepted :)

**Pull request merged**
