### PR TITLE
Added a readme

### PR DESCRIPTION
**Pull request by 1RedOne**
Hey man, love the project.  I think it would benefit from a readme, so I wrote one, based off of the project post.

### CODE REVIEW

**Comment by 1RedOne** [comment]
Hi @HiddenRambler , thoughts on adding this?

**Comment by Bombastisch** [comment]
I guess the thing is, you don't own the rights about this text! It's just copy pasted from GBAtemp and you didn't even use quotes nor asked the original writer if you can use his words. 

This might just bring @HiddenRambler in legal issues.

**Comment by Bombastisch** [comment]
If you rewrite the text or ask the original writer if you can use this as a Readme, he is good to go!

**Comment by HiddenRambler** [comment]
Thanks.

I wanted to read it throughly before I merged it and time was on short supply.

Does this have any text from anyone other than myself you or @Bombastisch?

**Comment by Bombastisch** [comment]
@HiddenRambler 

Oh, I'm sorry!  I was a bit confused.

Did you have an other name on GBAtemp before?

This text only contains your words and doesn't contain any other words by a third person.    

__You are good to go to merge it!__

**Comment by HiddenRambler** [comment]
Merged. Thank you both.

**Pull request merged**
