### PR TITLE
Show more amiibo info

### PR DESCRIPTION
**Pull request by North101**
Rewrite Amiibo data lookup. Data credits https://github.com/N3evin/AmiiboAPI. (json file from https://github.com/North101/AmiiboAPI/blob/wip/database/amiibo.json)
Show more info for tags (Game series, character, amiibo type, amiibo series)
Blank amiibo tags no longer show up as Mario
Allow MainActivity to scroll
MainActivity retains its loaded tag when recreated/rotated

screenshot_20170725-142211
screenshot_20170725-142228

### CODE REVIEW

**Comment by Bombastisch** [comment]
I have a small idea. Maybe you can think about it: 

Instead of hardcoding the Api.json (the file where the amiibo data is stored), you could make the program look online for the identification numbers at http://www.amiiboapi.com/api/amiibo

This would have the benefit that the online-list is continously updated and if new amiibos are released, there is no need to update the complete app!

I hope you put this into consideration.

**Comment by North101** [comment]
@Bombastisch I've considered that as well but then you are tied to a 3rd party service. I think maybe the best approach would be to have multiple ways:

1. embed
2. sync from 3rd party
3. load from json file (local or hosted)

**Comment by North101** [comment]
@Bombastisch Added the ability to load an external json file and also reset it back to the embedded one

**Comment by HiddenRambler** [comment]
The reason for not loading from a third party URL is at the moment i'm not using the android internet permission. 

@North101 I've not had time to check your changes yet will likely merge them in the weekend.

**Comment by North101** [comment]
@HiddenRambler https://github.com/N3evin/AmiiboAPI has merged my changes to their project so going forward you can just drag and drop the amiibo.json file into the assets folder to update it

**Comment by jmh363905** [comment]
I don't know if this is where this belongs, but in line with the topic of showing more info, have you thought about adding some graphical info?  I can help pull together whatever image files would be needed if you think this is an endeavor worth taking on. :) 

Example:
screenshot_2017-07-27-23-56-43

**Comment by North101** [comment]
@jmh363905 I considered it but decided not to add it. It would mean either embedding the images (which would inflate the size of the app by a lot) or relying on a 3rd party and most likely caching it.

https://github.com/N3evin/AmiiboAPI which I got the amiibo data from also has images which can be fetched by the amiibo id.

**Pull request merged**
